data<-read.table(pipe('findstr "^[1-2]/2/2007" "household_power_consumption.txt"'), sep=';', header=F, na.strings = "?")
colnames(data) <-names(read.table("household_power_consumption.txt", sep=";", header=T, nrows=1))
datetime <- strptime(paste(data$Date, data$Time), "%d/%m/%Y %H:%M:%S")
Sys.setlocale("LC_TIME", "English_United States.1252")
par(mfrow = c(2, 2))
plot(datetime, data$Global_active_power, ylab = "Global Active Power", xlab="",type="l")
plot(datetime, data$Voltage, ylab = "Voltage", xlab="datetime",type="l")
with(datetime, {
	plot(datetime,data$Sub_metering_1, type="l", ylab="Energy sub metering", xlab="")
	lines(datetime,data$Sub_metering_2,col="red")
	lines(datetime, data$Sub_metering_3,col="blue")
})
legend("topright", col = c("black", "red", "blue"), lty = 1, legend = c("Sub_metering_1", "Sub_metering_2", "Sub_metering_3"))
plot(datetime, data$Global_reactive_power, ylab = "Global_reactive_power", xlab="datetime",type="l")
dev.copy(png, file="plot4.png", height=480, width=480)
dev.off()